require("dotenv").config({ path: __dirname + "/../../.env" });
const mongoose = require("mongoose");
const bcrypt = require("bcrypt");
const ConnectDB = require("../config/database");
const User = require("../models/user");
const ConnectionRequest = require("../models/connection");
const Chat = require("../models/chat");

// 105 Curated Profiles (Famous Tech Icons, Indian Founders, AI Pioneers & Elite Developers)
const mockUsers = [
  // --- FOUNDERS & TECH LUMINARIES ---
  {
    firstName: "Dev",
    lastName: "Builder",
    email: "dev@gmail.com",
    plainPassword: "dev@123",
    age: 26,
    gender: "male",
    about: "Full-stack engineer building scalable web products. Passionate about React, Node.js, distributed systems, and clean software architecture.",
    lookingFor: "Technical Co-founders & Collaborators",
    skills: ["React", "Node.js", "Express", "MongoDB", "Tailwind CSS", "Redux", "TypeScript"],
    profilePictureUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Elon",
    lastName: "Musk",
    email: "elon@gmail.com",
    plainPassword: "elon@123",
    age: 52,
    gender: "male",
    about: "Engineering from first principles. Building reusable orbital rockets, electric vehicles, and high-bandwidth neural interfaces.",
    lookingFor: "Hardcore AI & Systems Engineers",
    skills: ["System Architecture", "Physics", "Autonomous Systems", "Product Strategy", "Manufacturing"],
    profilePictureUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Sam",
    lastName: "Altman",
    email: "sam@gmail.com",
    plainPassword: "sam@123",
    age: 39,
    gender: "male",
    about: "Scaling compute and intelligence to benefit humanity. Curious about energy abundance, fusion, and general intelligence.",
    lookingFor: "AI Researchers & Infrastructure Architects",
    skills: ["AI Research", "Venture Capital", "Product Scaling", "Leadership"],
    profilePictureUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Kunal",
    lastName: "Shah",
    email: "kunal@gmail.com",
    plainPassword: "kunal@123",
    age: 41,
    gender: "male",
    about: "Founder at CRED & Freecharge. Obsessed with high-trust communities, behavioral psychology, and the Delta-4 framework in Indian consumer tech.",
    lookingFor: "Product Thinkers & Fintech Mavericks",
    skills: ["Product Strategy", "Consumer Tech", "Fintech", "Behavioral Economics", "Mentorship"],
    profilePictureUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Deepinder",
    lastName: "Goyal",
    email: "deepinder@gmail.com",
    plainPassword: "deepinder@123",
    age: 41,
    gender: "male",
    about: "Founder & CEO at Zomato / Blinkit. Building lightning-fast hyperlocal commerce and obsessive culinary logistics.",
    lookingFor: "Hyperlocal Systems & Supply Chain Engineers",
    skills: ["Hyperlocal Logistics", "Product Operations", "Scaling", "Supply Chain", "Growth"],
    profilePictureUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Sarah",
    lastName: "Guo",
    email: "sarah@gmail.com",
    plainPassword: "sarah@123",
    age: 34,
    gender: "female",
    about: "Founder of Conviction. Early-stage investor backing technical founders building intelligent software. Previously partner at Greylock.",
    lookingFor: "Early-stage AI Founders",
    skills: ["Early Stage Investing", "AI Startups", "Go-To-Market", "Board Leadership"],
    profilePictureUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Jensen",
    lastName: "Huang",
    email: "jensen@gmail.com",
    plainPassword: "jensen@123",
    age: 61,
    gender: "male",
    about: "Accelerating computing for the era of generative AI and physical simulations. The more you buy, the more you save.",
    lookingFor: "CUDA & Parallel Compute Wizards",
    skills: ["GPU Computing", "CUDA", "Hardware Architecture", "Distributed Training", "Semiconductors"],
    profilePictureUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Nandan",
    lastName: "Nilekani",
    email: "nandan@gmail.com",
    plainPassword: "nandan@123",
    age: 69,
    gender: "male",
    about: "Architect of Aadhaar and India Stack. Co-founder of Infosys. Passionate about digital public infrastructure for a billion people.",
    lookingFor: "Public Infrastructure & Open Protocol Builders",
    skills: ["Digital Public Goods", "Identity Systems", "Distributed Architecture", "National Scale Tech"],
    profilePictureUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Nikhil",
    lastName: "Kamath",
    email: "nikhil@gmail.com",
    plainPassword: "nikhil@123",
    age: 38,
    gender: "male",
    about: "Co-founder of Zerodha and True Beacon. Bootstrapping capital markets and angel investing in young Indian entrepreneurs.",
    lookingFor: "Bootstrapped Founders & Capital Markets Innovators",
    skills: ["Fintech", "Financial Markets", "Angel Investing", "Bootstrapping", "Trading Systems"],
    profilePictureUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Satya",
    lastName: "Nadella",
    email: "satya@gmail.com",
    plainPassword: "satya@123",
    age: 56,
    gender: "male",
    about: "Empowering every person and organization on the planet to achieve more. Growth mindset, cloud infrastructure, and frontier AI.",
    lookingFor: "Enterprise Software & Cloud Innovators",
    skills: ["Cloud Computing", "Enterprise Tech", "Strategy", "Culture Transformation", "AI Partnerships"],
    profilePictureUrl: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Sundar",
    lastName: "Pichai",
    email: "sundar@gmail.com",
    plainPassword: "sundar@123",
    age: 52,
    gender: "male",
    about: "CEO at Alphabet & Google. Organizing the world's information and making it universally accessible through breakthrough machine learning.",
    lookingFor: "Search & Multimodal AI Engineers",
    skills: ["Product Leadership", "Global Infrastructure", "Machine Learning", "Strategic Partnerships"],
    profilePictureUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Linus",
    lastName: "Torvalds",
    email: "linus@gmail.com",
    plainPassword: "linus@123",
    age: 54,
    gender: "male",
    about: "Creator of the Linux kernel and Git. Clean C, zero bullshit, and high quality systems code.",
    lookingFor: "Kernel Hackers & Low-Level C Programmers",
    skills: ["C", "Linux Kernel", "Git", "OS Architecture", "Memory Management"],
    profilePictureUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Bhavish",
    lastName: "Aggarwal",
    email: "bhavish@gmail.com",
    plainPassword: "bhavish@123",
    age: 39,
    gender: "male",
    about: "Founder of Ola and Krutrim AI. Accelerating electric mobility and building sovereign AI compute stack for India.",
    lookingFor: "Autonomous Robotics & EV Firmware Engineers",
    skills: ["EV Powertrains", "Robotics", "Sovereign AI", "Manufacturing", "Fleet Operations"],
    profilePictureUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Vijay",
    lastName: "Sharma",
    email: "vijay@gmail.com",
    plainPassword: "vijay@123",
    age: 46,
    gender: "male",
    about: "Founder of Paytm. Digital payments pioneer bringing QR codes and soundboxes to every small merchant across India.",
    lookingFor: "UPI Protocol Architects & High Volume Payment Engineers",
    skills: ["Digital Payments", "Fintech", "UPI Protocols", "Merchant Networks"],
    profilePictureUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Ritesh",
    lastName: "Agarwal",
    email: "ritesh@gmail.com",
    plainPassword: "ritesh@123",
    age: 30,
    gender: "male",
    about: "Founder & CEO of OYO. Transforming global hospitality through dynamic pricing, IoT asset management, and franchise automation.",
    lookingFor: "Dynamic Pricing & Revenue Management Engineers",
    skills: ["Hospitality Tech", "Revenue Management", "Growth Hacking", "IoT"],
    profilePictureUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Sridhar",
    lastName: "Vembu",
    email: "sridhar@gmail.com",
    plainPassword: "sridhar@123",
    age: 56,
    gender: "male",
    about: "Founder & CEO of Zoho. Bootstrapping rural engineering centers and building the world's most comprehensive enterprise SaaS operating system.",
    lookingFor: "R&D Engineers for Deep-Tech Compilers & Databases",
    skills: ["Enterprise SaaS", "Bootstrapping", "R&D Management", "Database Engines"],
    profilePictureUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Girish",
    lastName: "Mathrubootham",
    email: "girish@gmail.com",
    plainPassword: "girish@123",
    age: 49,
    gender: "male",
    about: "Founder of Freshworks. Took India's first B2B SaaS startup to Nasdaq. Passionate about product-led growth and delighting customers.",
    lookingFor: "SaaS Go-To-Market & CRM Engineers",
    skills: ["B2B SaaS", "Product-Led Growth", "Customer Experience", "Nasdaq Listing"],
    profilePictureUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Tanmay",
    lastName: "Bhat",
    email: "tanmay@gmail.com",
    plainPassword: "tanmay@123",
    age: 37,
    gender: "male",
    about: "Creator, comedian, investor. Exploring viral growth, creator economies, meme marketing, and early tech angel investing.",
    lookingFor: "Creator Tool Founders & Viral Growth Marketers",
    skills: ["Creator Economy", "Viral Marketing", "Content Strategy", "Angel Investing"],
    profilePictureUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Radhika",
    lastName: "Gupta",
    email: "radhika@gmail.com",
    plainPassword: "radhika@123",
    age: 41,
    gender: "female",
    about: "MD & CEO at Edelweiss Mutual Fund. The girl with the broken neck who built a $15B+ asset management powerhouse.",
    lookingFor: "Quant Developers & Algorithmic Portfolio Analysts",
    skills: ["Asset Management", "Wealth Tech", "Risk Management", "Public Markets"],
    profilePictureUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Falguni",
    lastName: "Nayar",
    email: "falguni@gmail.com",
    plainPassword: "falguni@123",
    age: 61,
    gender: "female",
    about: "Founder & CEO of Nykaa. Pioneer in Indian beauty e-commerce and omnichannel retail, taking homegrown brands public.",
    lookingFor: "Omnichannel Logistics & Retail Tech Specialists",
    skills: ["E-Commerce", "Omnichannel Retail", "D2C Brands", "Capital Allocation"],
    profilePictureUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Ghazal",
    lastName: "Alagh",
    email: "ghazal@gmail.com",
    plainPassword: "ghazal@123",
    age: 36,
    gender: "female",
    about: "Co-founder of Mamaearth (Honasa Consumer). Building toxin-free D2C brands powered by customer data loops.",
    lookingFor: "D2C Analytics & Growth Engineers",
    skills: ["D2C Growth", "Brand Building", "Consumer Behavior", "Data Analytics"],
    profilePictureUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Vineeta",
    lastName: "Singh",
    email: "vineeta@gmail.com",
    plainPassword: "vineeta@123",
    age: 41,
    gender: "female",
    about: "Co-founder & CEO of SUGAR Cosmetics. Ironman triathlete passionate about resilient supply chains and high-velocity retail distribution.",
    lookingFor: "Performance Marketing & Retail Automation Engineers",
    skills: ["Brand Strategy", "Retail Distribution", "Supply Chain", "Performance Marketing"],
    profilePictureUrl: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Aman",
    lastName: "Gupta",
    email: "aman@gmail.com",
    plainPassword: "aman@123",
    age: 42,
    gender: "male",
    about: "Co-founder & CMO of boAt. Disrupting lifestyle audio and wearables with aggressive branding and value engineering.",
    lookingFor: "Wearable Hardware & Firmware Developers",
    skills: ["Consumer Electronics", "Marketing Strategy", "Supply Chain", "Brand Positioning"],
    profilePictureUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Peyush",
    lastName: "Bansal",
    email: "peyush@gmail.com",
    plainPassword: "peyush@123",
    age: 40,
    gender: "male",
    about: "Founder & CEO of Lenskart. Revolutionizing eyewear manufacturing, robotic lens assembly, and computer vision fitting.",
    lookingFor: "Computer Vision & Robotics Specialists",
    skills: ["Computer Vision", "Robotics", "Omnichannel Retail", "Manufacturing Tech"],
    profilePictureUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Anupam",
    lastName: "Mittal",
    email: "anupam@gmail.com",
    plainPassword: "anupam@123",
    age: 52,
    gender: "male",
    about: "Founder of Shaadi.com and People Group. Active angel investor backing 200+ innovative tech startups across India.",
    lookingFor: "Marketplace & Consumer Social Founders",
    skills: ["Marketplace Dynamics", "Angel Investing", "Consumer Internet", "Product Design"],
    profilePictureUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Ashneer",
    lastName: "Grover",
    email: "ashneer@gmail.com",
    plainPassword: "ashneer@123",
    age: 42,
    gender: "male",
    about: "Fintech founder & author of Doglapan. Zero sugarcoating, high-speed execution, and unit economic rigor.",
    lookingFor: "Aggressive Execution Engineers & Growth Hackers",
    skills: ["Fintech", "Merchant Finance", "Growth Hacking", "Unit Economics"],
    profilePictureUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },

  // --- AI PIONEERS & SCIENTISTS ---
  {
    firstName: "Andrej",
    lastName: "Karpathy",
    email: "andrej@gmail.com",
    plainPassword: "andrej@123",
    age: 38,
    gender: "male",
    about: "Former Director of AI at Tesla and OpenAI founding team. Teaching machines to see and humans to build neural networks from scratch.",
    lookingFor: "LLM Architects & CUDA Optimizer Specialists",
    skills: ["PyTorch", "LLMs", "Deep Learning", "Computer Vision", "CUDA"],
    profilePictureUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Ilya",
    lastName: "Sutskever",
    email: "ilya@gmail.com",
    plainPassword: "ilya@123",
    age: 38,
    gender: "male",
    about: "Co-founder of Safe Superintelligence Inc. (SSI) and former Chief Scientist at OpenAI. Dedicated to superintelligence alignment.",
    lookingFor: "AI Alignment & Safety Researchers",
    skills: ["Deep Learning Theory", "Transformer Architectures", "AI Alignment", "Information Theory"],
    profilePictureUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Demis",
    lastName: "Hassabis",
    email: "demis@gmail.com",
    plainPassword: "demis@123",
    age: 48,
    gender: "male",
    about: "Nobel Laureate in Chemistry, Founder & CEO of Google DeepMind. Solved protein folding with AlphaFold. Advancing artificial general intelligence.",
    lookingFor: "Bio-ML Researchers & Reinforcement Learning Scientists",
    skills: ["AlphaFold", "Reinforcement Learning", "Neuroscience", "Computational Biology"],
    profilePictureUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Yann",
    lastName: "LeCun",
    email: "yann@gmail.com",
    plainPassword: "yann@123",
    age: 64,
    gender: "male",
    about: "Turing Award Laureate, Chief AI Scientist at Meta. Pioneered CNNs, self-supervised learning, and Joint Embedding Predictive Architectures (JEPA).",
    lookingFor: "World Model & Self-Supervised Learning Researchers",
    skills: ["Self-Supervised Learning", "JEPA", "Computer Vision", "Open Source AI"],
    profilePictureUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Priya",
    lastName: "Sharma",
    email: "priya@gmail.com",
    plainPassword: "priya@123",
    age: 27,
    gender: "female",
    about: "AI researcher focusing on model quantization, vLLM optimizations, and low-latency inference on edge silicon.",
    lookingFor: "GPU Kernel Programmers & ML Systems Builders",
    skills: ["Python", "PyTorch", "vLLM", "Triton", "Quantization", "FastAPI"],
    profilePictureUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },

  // --- OPEN SOURCE & SOFTWARE GIANTS ---
  {
    firstName: "Guillermo",
    lastName: "Rauch",
    email: "guillermo@gmail.com",
    plainPassword: "guillermo@123",
    age: 33,
    gender: "male",
    about: "CEO at Vercel. Creator of Next.js, Socket.io, and Mongoose. Making the web fundamentally faster and developer experience delightful.",
    lookingFor: "Edge Runtime & Compiler Engineers",
    skills: ["Next.js", "Edge Compute", "Turbopack", "Socket.io", "Vercel"],
    profilePictureUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Dan",
    lastName: "Abramov",
    email: "dan@gmail.com",
    plainPassword: "dan@123",
    age: 32,
    gender: "male",
    about: "Co-creator of Redux and Create React App, core React team alum. Exploring mental models, React Server Components, and simple UI systems.",
    lookingFor: "Frontend Architects & Spec Authors",
    skills: ["React", "Redux", "JavaScript", "Server Components", "API Design"],
    profilePictureUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Sophie",
    lastName: "Alpert",
    email: "sophie@gmail.com",
    plainPassword: "sophie@123",
    age: 33,
    gender: "female",
    about: "Former manager of the React core team, engineering leadership at Khan Academy. Building modern educational tooling and accessible frontends.",
    lookingFor: "Education Tech & Design System Collaborators",
    skills: ["React", "TypeScript", "Accessibility", "Design Systems", "Web Performance"],
    profilePictureUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Patrick",
    lastName: "Collison",
    email: "patrick@gmail.com",
    plainPassword: "patrick@123",
    age: 35,
    gender: "male",
    about: "Co-founder & CEO of Stripe. Increasing the GDP of the internet with developer-first financial infrastructure.",
    lookingFor: "Distributed Financial Protocol Engineers",
    skills: ["Distributed Systems", "API Design", "Financial Rails", "Ruby", "Infrastructure"],
    profilePictureUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "John",
    lastName: "Collison",
    email: "john@gmail.com",
    plainPassword: "john@123",
    age: 33,
    gender: "male",
    about: "President & Co-founder of Stripe. Scaling global commerce, billing engines, and cross-border payments.",
    lookingFor: "Global Billing & Compliance Architects",
    skills: ["Fintech", "Payment Gateways", "Global Commerce", "Product Strategy"],
    profilePictureUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Brian",
    lastName: "Chesky",
    email: "brian@gmail.com",
    plainPassword: "brian@123",
    age: 43,
    gender: "male",
    about: "Co-founder & CEO of Airbnb. Industrial design graduate turned tech founder. Focused on product design, taste, and hospitality.",
    lookingFor: "Taste-Driven Product Designers & Fullstack Engineers",
    skills: ["Product Design", "Hospitality Tech", "Brand Storytelling", "Taste"],
    profilePictureUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Paul",
    lastName: "Graham",
    email: "paul@gmail.com",
    plainPassword: "paul@123",
    age: 59,
    gender: "male",
    about: "Co-founder of Y Combinator and Viaweb. Author of Hackers & Painters. Essays on startups, programming languages, and relentlessly resourceful founders.",
    lookingFor: "Relentlessly Resourceful Early-Stage Founders",
    skills: ["Startup Incubation", "Lisp", "Angel Investing", "Philosophy", "Essays"],
    profilePictureUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Marc",
    lastName: "Andreessen",
    email: "marc@gmail.com",
    plainPassword: "marc@123",
    age: 53,
    gender: "male",
    about: "Co-founder of a16z and Netscape. Software is eating the world, and techno-optimism is the path forward.",
    lookingFor: "Frontier Tech & Defense Founders",
    skills: ["Venture Capital", "Browser Architecture", "Macroeconomics", "Techno-Optimism"],
    profilePictureUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Pieter",
    lastName: "Levels",
    email: "levels@gmail.com",
    plainPassword: "levels@123",
    age: 37,
    gender: "male",
    about: "Solopreneur building Nomad List, RemoteOK, PhotoAI. 1 developer, zero frameworks, vanilla PHP/JS, running on a single VPS.",
    lookingFor: "Indie Hackers & Solo SaaS Builders",
    skills: ["Indie Hacking", "Vanilla JS", "PHP", "SQLite", "Automation", "SEO"],
    profilePictureUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Nat",
    lastName: "Friedman",
    email: "nat@gmail.com",
    plainPassword: "nat@123",
    age: 47,
    gender: "male",
    about: "Former CEO of GitHub, angel investor backing AI research (AI Grant, Vesuvius Challenge). Championing open source computing.",
    lookingFor: "Open Science & Autonomous AI Agent Researchers",
    skills: ["Open Source", "Developer Tools", "AI Grant", "GitHub", "Angel Investing"],
    profilePictureUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Kelsey",
    lastName: "Hightower",
    email: "kelsey@gmail.com",
    plainPassword: "kelsey@123",
    age: 43,
    gender: "male",
    about: "Staff Developer Advocate, Kubernetes pioneer, author of Kubernetes Up & Running. Simplifying distributed infrastructure for developers.",
    lookingFor: "Kubernetes & Cloud Native Tooling Builders",
    skills: ["Kubernetes", "Go", "Docker", "DevOps", "Cloud Architecture"],
    profilePictureUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Mitchell",
    lastName: "Hashimoto",
    email: "mitchell@gmail.com",
    plainPassword: "mitchell@123",
    age: 35,
    gender: "male",
    about: "Founder of HashiCorp (Terraform, Vagrant, Consul, Vault). Now building high-performance terminal emulators in Zig (Ghostty).",
    lookingFor: "Zig & Systems Tooling Programmers",
    skills: ["Zig", "Go", "Infrastructure as Code", "Terraform", "Terminal Emulation"],
    profilePictureUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Guido",
    lastName: "van Rossum",
    email: "guido@gmail.com",
    plainPassword: "guido@123",
    age: 68,
    gender: "male",
    about: "Benevolent Dictator for Life (emeritus) of Python. Optimizing CPython interpreter performance at Microsoft.",
    lookingFor: "Language Runtime & Bytecode Optimization Specialists",
    skills: ["Python", "C", "Compiler Design", "Language Runtime", "CPython"],
    profilePictureUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Brendan",
    lastName: "Eich",
    email: "brendan@gmail.com",
    plainPassword: "brendan@123",
    age: 63,
    gender: "male",
    about: "Creator of JavaScript, co-founder of Mozilla and Brave. Pioneering privacy-first web browsing and the Basic Attention Token.",
    lookingFor: "Browser Engine & Cryptographic Token Builders",
    skills: ["JavaScript", "C++", "Browser Architecture", "Cryptography", "Rust"],
    profilePictureUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Ada",
    lastName: "Lovelace",
    email: "ada@gmail.com",
    plainPassword: "ada@1234",
    age: 29,
    gender: "female",
    about: "First computer programmer in history. Writing algorithmic compilers and formally verified systems in Rust.",
    lookingFor: "Compilers & Formal Verification Engineers",
    skills: ["Algorithms", "Compilers", "Rust", "Mathematics", "Formal Methods"],
    profilePictureUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Grace",
    lastName: "Hopper",
    email: "grace@gmail.com",
    plainPassword: "grace@123",
    age: 35,
    gender: "female",
    about: "Pioneered machine-independent programming languages and invented the first compiler. Obsessed with nanosecond latencies.",
    lookingFor: "Low-Latency Systems & Distributed Database Authors",
    skills: ["Compilers", "Static Analysis", "Go", "Hardware Interconnects", "Distributed Systems"],
    profilePictureUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },

  // --- INDIAN TECH BUILDERS & LEADING TALENT (50+ Curated Profiles) ---
  {
    firstName: "Aarav",
    lastName: "Verma",
    email: "aarav@gmail.com",
    plainPassword: "aarav@123",
    age: 28,
    gender: "male",
    about: "Senior backend engineer specializing in high-throughput payment pipelines and distributed transaction settlement in Go and Kafka.",
    lookingFor: "Fintech Co-founders & Distributed Systems Geeks",
    skills: ["Go", "Kafka", "PostgreSQL", "Redis", "Distributed Transactions", "Docker"],
    profilePictureUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Ananya",
    lastName: "Deshmukh",
    email: "ananya@gmail.com",
    plainPassword: "ananya@123",
    age: 26,
    gender: "female",
    about: "Frontend engineer at a unicorn startup. Crafting high-fidelity UI animations, accessible component libraries, and micro-interactions.",
    lookingFor: "Product Designers & Fullstack Collaborators",
    skills: ["React", "TypeScript", "Tailwind CSS", "Motion", "Storybook", "Next.js"],
    profilePictureUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Aditya",
    lastName: "Kulkarni",
    email: "aditya@gmail.com",
    plainPassword: "aditya@123",
    age: 30,
    gender: "male",
    about: "Staff Site Reliability Engineer. Scaling Kubernetes clusters across multi-cloud regions with zero downtime deployments.",
    lookingFor: "DevOps & Infrastructure Lead roles",
    skills: ["Kubernetes", "Terraform", "Prometheus", "AWS", "Go", "ArgoCD"],
    profilePictureUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Sneha",
    lastName: "Iyer",
    email: "sneha@gmail.com",
    plainPassword: "sneha@123",
    age: 25,
    gender: "female",
    about: "Computer vision engineer training custom object detection and segmentation models for autonomous drones and smart retail.",
    lookingFor: "Robotics & Edge AI Collaborators",
    skills: ["PyTorch", "OpenCV", "TensorRT", "Python", "YOLO", "C++"],
    profilePictureUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Kavya",
    lastName: "Menon",
    email: "kavya@gmail.com",
    plainPassword: "kavya@123",
    age: 29,
    gender: "female",
    about: "Product manager leading consumer retention and growth experiments. Data-informed, user-obsessed, and rapid iterative shipper.",
    lookingFor: "Growth Engineers & Early Stage Founders",
    skills: ["Product Management", "Growth Hacking", "Mixpanel", "SQL", "User Research"],
    profilePictureUrl: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Rahul",
    lastName: "Nair",
    email: "rahul@gmail.com",
    plainPassword: "rahul@123",
    age: 31,
    gender: "male",
    about: "Full stack developer who built 4 micro-SaaS products to $10k MRR. Clean architectures, fast shipping, and automated customer acquisition.",
    lookingFor: "Indie Hackers & Content Creators",
    skills: ["React", "Next.js", "Node.js", "Supabase", "Stripe", "Tailwind CSS"],
    profilePictureUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Meera",
    lastName: "Reddy",
    email: "meera@gmail.com",
    plainPassword: "meera@123",
    age: 27,
    gender: "female",
    about: "Lead UI/UX designer. Transforming dense financial workflows into intuitive, beautiful experiences. Figma components enthusiast.",
    lookingFor: "Design System Engineers & Mobile Devs",
    skills: ["Figma", "UI/UX Design", "Design Systems", "Prototyping", "User Research"],
    profilePictureUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Ishaan",
    lastName: "Gupta",
    email: "ishaan@gmail.com",
    plainPassword: "ishaan@123",
    age: 24,
    gender: "male",
    about: "Rust developer writing ultra-low latency websocket gateways and custom matching engines for algorithmic trading desks.",
    lookingFor: "Quant Traders & Rustaceans",
    skills: ["Rust", "WebSockets", "Tokio", "High Frequency Trading", "C++", "Linux"],
    profilePictureUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Diya",
    lastName: "Choudhury",
    email: "diya@gmail.com",
    plainPassword: "diya@123",
    age: 28,
    gender: "female",
    about: "Data platform engineer managing petabyte-scale data lakes with Apache Spark, Iceberg, and dbt. Loves clean data lineage.",
    lookingFor: "Analytics Engineers & ML Ops Teams",
    skills: ["Apache Spark", "Python", "SQL", "dbt", "Snowflake", "Kafka"],
    profilePictureUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Siddharth",
    lastName: "Bose",
    email: "siddharth@gmail.com",
    plainPassword: "siddharth@123",
    age: 33,
    gender: "male",
    about: "Mobile architect. Leading Flutter and iOS engineering for a 10M+ MAU health tech app. Passionate about offline-first sync.",
    lookingFor: "Mobile Developers & HealthTech Founders",
    skills: ["Flutter", "Swift", "Dart", "Offline Sync", "RxJava", "CI/CD"],
    profilePictureUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Tara",
    lastName: "Chatterjee",
    email: "tara@gmail.com",
    plainPassword: "tara@123",
    age: 26,
    gender: "female",
    about: "Security engineer and ethical hacker. Specializing in cloud penetration testing, smart contract audits, and DevSecOps pipelines.",
    lookingFor: "Security Founders & Web3 Devs",
    skills: ["Cybersecurity", "Penetration Testing", "Solidity", "AWS Security", "OWASP"],
    profilePictureUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Varun",
    lastName: "Kapoor",
    email: "varun@gmail.com",
    plainPassword: "varun@123",
    age: 29,
    gender: "male",
    about: "Machine learning engineer building RAG architectures and autonomous tool-calling agents for enterprise document intelligence.",
    lookingFor: "AI App Developers & Enterprise Founders",
    skills: ["Python", "LangChain", "LlamaIndex", "Vector DBs", "OpenAI API", "Docker"],
    profilePictureUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Pooja",
    lastName: "Hegde",
    email: "pooja@gmail.com",
    plainPassword: "pooja@123",
    age: 25,
    gender: "female",
    about: "Frontend developer focused on Web Performance and Core Web Vitals optimization. Turning 5-second sluggish sites into instant 60fps apps.",
    lookingFor: "React Engineers & Technical Writers",
    skills: ["React", "JavaScript", "Web Vitals", "Lighthouse", "CSS Architecture", "Vite"],
    profilePictureUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "basic",
  },
  {
    firstName: "Gaurav",
    lastName: "Sen",
    email: "gaurav@gmail.com",
    plainPassword: "gaurav@123",
    age: 32,
    gender: "male",
    about: "System design educator and distributed systems engineer. Helping developers master system architecture from caches to consensus protocols.",
    lookingFor: "Systems Educators & Senior Backend Engineers",
    skills: ["System Design", "Distributed Systems", "Java", "Redis", "Microservices"],
    profilePictureUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Simran",
    lastName: "Kaur",
    email: "simran@gmail.com",
    plainPassword: "simran@123",
    age: 28,
    gender: "female",
    about: "Backend developer building real-time collaboration engines and canvas whiteboards using WebSockets and operational transforms.",
    lookingFor: "Canvas Developers & Collaboration App Founders",
    skills: ["Node.js", "WebSockets", "CRDTs", "Redis", "TypeScript", "Express"],
    profilePictureUrl: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Kabir",
    lastName: "Bhatia",
    email: "kabir@gmail.com",
    plainPassword: "kabir@123",
    age: 27,
    gender: "male",
    about: "Three.js and WebGL developer. Creating immersive 3D web experiences, spatial interactive sites, and creative shaders.",
    lookingFor: "Creative Directors & WebGL Designers",
    skills: ["Three.js", "WebGL", "GLSL Shaders", "React Three Fiber", "Blender"],
    profilePictureUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Rhea",
    lastName: "Pillai",
    email: "rhea@gmail.com",
    plainPassword: "rhea@123",
    age: 26,
    gender: "female",
    about: "DevOps engineer orchestrating GitHub Actions CI/CD pipelines, automated testing harnesses, and automated canary rollouts.",
    lookingFor: "Cloud Engineers & Open Source Maintainers",
    skills: ["GitHub Actions", "Docker", "AWS", "Bash", "Terraform", "Python"],
    profilePictureUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "basic",
  },
  {
    firstName: "Akash",
    lastName: "Tripathi",
    email: "akash@gmail.com",
    plainPassword: "akash@123",
    age: 29,
    gender: "male",
    about: "Database reliability engineer. Tuning PostgreSQL queries, partitioning billion-row tables, and managing Redis clusters.",
    lookingFor: "Database Architects & High Scale Backend Founders",
    skills: ["PostgreSQL", "Database Tuning", "Redis", "Query Optimization", "Linux"],
    profilePictureUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Nisha",
    lastName: "Verma",
    email: "nisha@gmail.com",
    plainPassword: "nisha@123",
    age: 27,
    gender: "female",
    about: "Cross-platform mobile engineer building iOS and Android apps in React Native with JSI and native turbo modules.",
    lookingFor: "React Native Developers & Mobile Product Managers",
    skills: ["React Native", "TypeScript", "Redux", "iOS", "Android", "Jest"],
    profilePictureUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "basic",
  },
  {
    firstName: "Devika",
    lastName: "Nair",
    email: "devika@gmail.com",
    plainPassword: "devika@123",
    age: 30,
    gender: "female",
    about: "Engineering manager leading teams of 15+ backend and platform engineers. Servant leadership, clean engineering metrics, and high morale.",
    lookingFor: "Technical Directors & Founders scaling engineering teams",
    skills: ["Engineering Management", "Agile", "System Architecture", "Hiring", "Mentorship"],
    profilePictureUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Alok",
    lastName: "Pandey",
    email: "alok@gmail.com",
    plainPassword: "alok@123",
    age: 34,
    gender: "male",
    about: "Principal engineer specializing in distributed consensus (Raft, Paxos) and transactional storage engines.",
    lookingFor: "Distributed Systems Researchers",
    skills: ["Go", "Raft", "Distributed Consensus", "C++", "gRPC", "Protobuf"],
    profilePictureUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Shreya",
    lastName: "Ghosh",
    email: "shreya@gmail.com",
    plainPassword: "shreya@123",
    age: 26,
    gender: "female",
    about: "Full stack developer passionate about building developer tools, CLI utilities, and rich terminal interfaces.",
    lookingFor: "DevTools Founders & Open Source Collaborators",
    skills: ["Node.js", "TypeScript", "Rust", "Ink CLI", "Commander.js", "Git"],
    profilePictureUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "basic",
  },
  {
    firstName: "Pranav",
    lastName: "Saxena",
    email: "pranav@gmail.com",
    plainPassword: "pranav@123",
    age: 28,
    gender: "male",
    about: "Cloud security engineer setting up IAM least privilege, SOC2 compliance automation, and AWS security incident response.",
    lookingFor: "SOC2 Compliance Leads & Security Engineers",
    skills: ["AWS IAM", "Terraform", "CloudTrail", "SOC2", "Python", "Kubernetes"],
    profilePictureUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "basic",
  },
  {
    firstName: "Bhavna",
    lastName: "Joshi",
    email: "bhavna@gmail.com",
    plainPassword: "bhavna@123",
    age: 29,
    gender: "female",
    about: "Growth engineer specializing in onboarding funnel optimization, SEO rendering architecture, and A/B test pipelines.",
    lookingFor: "Product Leads & Growth Marketers",
    skills: ["Next.js", "Growth Engineering", "SEO", "PostHog", "TypeScript"],
    profilePictureUrl: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Abhishek",
    lastName: "Mishra",
    email: "abhishek@gmail.com",
    plainPassword: "abhishek@123",
    age: 32,
    gender: "male",
    about: "Staff software engineer. Architected event-driven microservices handling 50k requests per second during flash sales.",
    lookingFor: "Scalable E-Commerce & Event Driven Architecture Founders",
    skills: ["Java", "Spring Boot", "Kafka", "Redis", "Distributed Caching", "AWS"],
    profilePictureUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Kritika",
    lastName: "Malhotra",
    email: "kritika@gmail.com",
    plainPassword: "kritika@123",
    age: 27,
    gender: "female",
    about: "Frontend performance consultant. Auditing hydration overhead, bundle tree shaking, and code splitting in React apps.",
    lookingFor: "Frontend Architects & Performance Enthusiasts",
    skills: ["React", "Performance", "Webpack", "Vite", "JavaScript", "Profiling"],
    profilePictureUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Manish",
    lastName: "Dubey",
    email: "manish@gmail.com",
    plainPassword: "manish@123",
    age: 30,
    gender: "male",
    about: "Solidity smart contract developer. Written and deployed audited DeFi vaults, staking protocols, and ERC-4337 account abstraction.",
    lookingFor: "Web3 Protocols & DeFi Builders",
    skills: ["Solidity", "Hardhat", "Foundry", "EVM", "Ethereum", "Ethers.js"],
    profilePictureUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Tanvi",
    lastName: "Bansal",
    email: "tanvi@gmail.com",
    plainPassword: "tanvi@123",
    age: 26,
    gender: "female",
    about: "NLP data scientist fine-tuning small language models (Phi, Mistral) for Indian regional language question answering.",
    lookingFor: "Linguistics Researchers & AI Scientists",
    skills: ["Python", "HuggingFace", "LoRA", "Transformers", "PyTorch"],
    profilePictureUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Suresh",
    lastName: "Raina",
    email: "suresh@gmail.com",
    plainPassword: "suresh@123",
    age: 35,
    gender: "male",
    about: "Sports analytics engineer tracking biometric sensor feeds and building high-speed computer vision pitch tracking models.",
    lookingFor: "Sports Tech & IoT Engineers",
    skills: ["Python", "Computer Vision", "IoT Sensors", "TimeSeries DB", "C++"],
    profilePictureUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "basic",
  },
  {
    firstName: "Divya",
    lastName: "Prasad",
    email: "divya@gmail.com",
    plainPassword: "divya@123",
    age: 28,
    gender: "female",
    about: "Brand strategist and product copywriter. Crafting developer documentation, landing pages, and voice-and-tone frameworks.",
    lookingFor: "Developer Advocates & Technical Founders",
    skills: ["Technical Writing", "Copywriting", "Developer Marketing", "Content Strategy"],
    profilePictureUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "basic",
  },
  {
    firstName: "Rajesh",
    lastName: "Kannan",
    email: "rajesh@gmail.com",
    plainPassword: "rajesh@123",
    age: 36,
    gender: "male",
    about: "Embedded software engineer writing real-time operating system (FreeRTOS) drivers and BLE stacks for connected IoT hardware.",
    lookingFor: "Hardware Founders & Firmware Developers",
    skills: ["C", "FreeRTOS", "Embedded Systems", "BLE", "STM32", "Hardware Debugging"],
    profilePictureUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Sunita",
    lastName: "Rao",
    email: "sunita@gmail.com",
    plainPassword: "sunita@123",
    age: 33,
    gender: "female",
    about: "Lead quality architect. Building end-to-end Cypress and Playwright automated testing grids with continuous CI integration.",
    lookingFor: "QA Automation Engineers & Engineering Leads",
    skills: ["Playwright", "Cypress", "JavaScript", "Selenium", "Test Architecture"],
    profilePictureUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "basic",
  },
  {
    firstName: "Ajay",
    lastName: "Panigrahi",
    email: "ajaybpanigrahi@gmail.com",
    plainPassword: "ajay@123",
    age: 26,
    gender: "male",
    about: "Software engineer obsessed with WebSockets, real-time distributed chat systems, and modern web application craft.",
    lookingFor: "Ambitious Founders & Real-Time Engineering Collaborators",
    skills: ["Node.js", "React", "Socket.io", "MongoDB", "Express", "System Design"],
    profilePictureUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },

  // --- ADDITIONAL GLOBAL BUILDERS & FOUNDERS (to exceed 100+ profiles) ---
  {
    firstName: "Alex",
    lastName: "Morgan",
    email: "alex@gmail.com",
    plainPassword: "alex@123",
    age: 28,
    gender: "female",
    about: "Product designer crafting modern web interfaces, micro-interactions, and design systems that users genuinely love.",
    lookingFor: "Full-stack Developers for SaaS MVP",
    skills: ["UI/UX Design", "Figma", "Design Systems", "Tailwind CSS", "Motion Design"],
    profilePictureUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "James",
    lastName: "Gosling",
    email: "james@gmail.com",
    plainPassword: "james@123",
    age: 68,
    gender: "male",
    about: "Father of Java. Designing object-oriented programming runtimes, garbage collectors, and resilient virtual machines.",
    lookingFor: "Virtual Machine & JVM Specialists",
    skills: ["Java", "JVM", "Language Design", "Compilers", "Distributed Computing"],
    profilePictureUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Kai",
    lastName: "Chen",
    email: "kai@gmail.com",
    plainPassword: "kai@1234",
    age: 31,
    gender: "male",
    about: "Staff engineer at a fintech unicorn. Building high-throughput payment pipelines handling $10B+ in annual volume.",
    lookingFor: "Distributed Systems Geeks & Rustaceans",
    skills: ["Kafka", "Go", "PostgreSQL", "Redis", "Distributed Transactions"],
    profilePictureUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Mira",
    lastName: "Patel",
    email: "mira@gmail.com",
    plainPassword: "mira@123",
    age: 24,
    gender: "female",
    about: "Frontend enthusiast building accessible, keyboard-first web applications. Active contributor to open-source UI libraries.",
    lookingFor: "Open-source Collaborators & Frontend Leads",
    skills: ["React", "A11y", "Web Vitals", "Storybook", "TypeScript"],
    profilePictureUrl: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "basic",
  },
  {
    firstName: "Raj",
    lastName: "Kumar",
    email: "raj@gmail.com",
    plainPassword: "raj@1234",
    age: 33,
    gender: "male",
    about: "Cross-platform mobile engineer. Built and scaled apps with 10M+ downloads using Flutter, React Native, and native bridges.",
    lookingFor: "Mobile-first Startup Founders",
    skills: ["Flutter", "React Native", "Firebase", "Dart", "Swift", "Kotlin"],
    profilePictureUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Elena",
    lastName: "Rossi",
    email: "elena@gmail.com",
    plainPassword: "elena@123",
    age: 30,
    gender: "female",
    about: "Data engineer wrangling massive datasets with Apache Spark, Airflow, and Snowflake. Passionate about data lineage and pipeline observability.",
    lookingFor: "Data Science Teams & Analytics Engineers",
    skills: ["Python", "Spark", "MLflow", "Snowflake", "dbt", "Airflow"],
    profilePictureUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Marcus",
    lastName: "Johnson",
    email: "marcus@gmail.com",
    plainPassword: "marcus@123",
    age: 37,
    gender: "male",
    about: "DevOps & Cloud Architect specializing in multi-region AWS deployments, Kubernetes cluster scaling, and zero-trust security architecture.",
    lookingFor: "Early-stage Startups Needing DevOps Foundation",
    skills: ["Cybersecurity", "Penetration Testing", "AWS", "Terraform", "Kubernetes"],
    profilePictureUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Yuki",
    lastName: "Tanaka",
    email: "yuki@gmail.com",
    plainPassword: "yuki@123",
    age: 26,
    gender: "female",
    about: "Creative coder blending WebGL, Three.js, and generative AI to produce mind-bending interactive 3D web experiences.",
    lookingFor: "Creative Agencies & Innovative Product Teams",
    skills: ["Three.js", "WebGL", "p5.js", "GLSL", "Blender", "GSAP"],
    profilePictureUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Omar",
    lastName: "Hassan",
    email: "omar@gmail.com",
    plainPassword: "omar@123",
    age: 40,
    gender: "male",
    about: "Platform engineer obsessed with developer productivity. Building internal developer platforms (IDPs) and GitOps pipelines.",
    lookingFor: "Scale-ups Looking to Accelerate Dev Velocity",
    skills: ["Kubernetes", "ArgoCD", "Prometheus", "Helm", "Go", "Backstage"],
    profilePictureUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Nina",
    lastName: "Fernandez",
    email: "nina@gmail.com",
    plainPassword: "nina@123",
    age: 29,
    gender: "female",
    about: "Growth engineer combining code and behavioral psychology to optimize conversion funnels, onboarding flows, and product viral loops.",
    lookingFor: "Product-led Growth Startups",
    skills: ["Growth Hacking", "SQL", "Amplitude", "A/B Testing", "Mixpanel"],
    profilePictureUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "basic",
  },
  {
    firstName: "Arjun",
    lastName: "Mehta",
    email: "arjun@gmail.com",
    plainPassword: "arjun@123",
    age: 32,
    gender: "male",
    about: "Blockchain engineer developing smart contracts, zero-knowledge proof circuits, and cross-chain bridge protocols in Rust.",
    lookingFor: "DeFi Protocols & Web3 Infrastructure Teams",
    skills: ["Solidity", "ZK-proofs", "Rust", "EVM", "Hardhat", "Foundry"],
    profilePictureUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Sophie",
    lastName: "Laurent",
    email: "sophie.l@gmail.com",
    plainPassword: "sophie@123",
    age: 27,
    gender: "female",
    about: "Developer relations engineer and technical writer. Turning complex architectural concepts into crystal-clear documentation and guides.",
    lookingFor: "Developer-tool Companies Building DevRel",
    skills: ["Technical Writing", "API Design", "Community", "Open Source", "Docs-as-Code"],
    profilePictureUrl: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "basic",
  },
  {
    firstName: "Vikram",
    lastName: "Singh",
    email: "vikram@gmail.com",
    plainPassword: "vikram@123",
    age: 45,
    gender: "male",
    about: "Serial B2B SaaS founder with 2 exits. Angel investing in enterprise software, vertical SaaS, and AI-powered productivity tools.",
    lookingFor: "Seed-stage B2B SaaS Founders",
    skills: ["Fundraising", "B2B SaaS", "Go-To-Market", "Enterprise Sales", "M&A"],
    profilePictureUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "premium",
  },
  {
    firstName: "Zara",
    lastName: "Ali",
    email: "zara@gmail.com",
    plainPassword: "zara@123",
    age: 25,
    gender: "female",
    about: "iOS developer crafting buttery-smooth apps with SwiftUI and Combine. Obsessed with Apple HIG, animations, and typography.",
    lookingFor: "Consumer Apps with High Design Standards",
    skills: ["Swift", "SwiftUI", "UIKit", "Combine", "CoreData", "Metal"],
    profilePictureUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "basic",
  },
  {
    firstName: "Leo",
    lastName: "Nakamura",
    email: "leo@gmail.com",
    plainPassword: "leo@1234",
    age: 34,
    gender: "male",
    about: "Game developer and real-time graphics engineer. Building multiplayer game backends using WebSockets, WebTransport, and custom UDP protocols.",
    lookingFor: "Game Studios & Virtual World Builders",
    skills: ["WebSockets", "Unity", "C#", "C++", "Networking", "Shader Graph"],
    profilePictureUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Anya",
    lastName: "Petrov",
    email: "anya@gmail.com",
    plainPassword: "anya@123",
    age: 28,
    gender: "female",
    about: "NLP researcher specializing in multilingual language models. Building tools to make AI understand low-resource languages.",
    lookingFor: "NLP & Linguistics Researchers",
    skills: ["NLP", "Transformers", "HuggingFace", "Python", "FastAPI"],
    profilePictureUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Daniel",
    lastName: "Kim",
    email: "daniel@gmail.com",
    plainPassword: "daniel@123",
    age: 36,
    gender: "male",
    about: "Startup CTO who loves building v1 products from scratch. Expert at choosing the right tech stack for speed vs scale trade-offs.",
    lookingFor: "Non-technical Founders with Big Ideas",
    skills: ["Next.js", "Prisma", "Vercel", "Stripe", "PostgreSQL"],
    profilePictureUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "pro",
  },
  {
    firstName: "Ram",
    lastName: "Raj",
    email: "ram@gmail.com",
    plainPassword: "ram@1234",
    age: 29,
    gender: "male",
    about: "Full stack developer interested in scalable cloud databases, GraphQL APIs, and clean serverless functions.",
    lookingFor: "Serverless & GraphQL Enthusiasts",
    skills: ["GraphQL", "AWS Lambda", "Node.js", "DynamoDB", "TypeScript"],
    profilePictureUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "basic",
  },
  {
    firstName: "Shyam",
    lastName: "Naam",
    email: "shyam@gmail.com",
    plainPassword: "shyam@123",
    age: 32,
    gender: "male",
    about: "Passionate developer exploring spiritual tech, meditation apps, and tranquil digital spaces. Aham Brahmasmi.",
    lookingFor: "Mindful Tech Builders & Philosophers",
    skills: ["React Native", "Audio Streaming", "Node.js", "UI Design", "Mental Wellness"],
    profilePictureUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&crop=faces&w=800&q=80",
    membershipType: "basic",
  },
];

// Generate additional realistic developers to reach over 105 profiles
const additionalIndianNames = [
  { f: "Karan", l: "Singhania", g: "male", s: ["React", "Express", "PostgreSQL", "Docker"], a: "Building fintech microservices and consumer credit platforms." },
  { f: "Pallavi", l: "Bhardwaj", g: "female", s: ["UI/UX", "Figma", "Tailwind CSS", "Motion"], a: "Passionate about inclusive design systems and fluid micro-interactions." },
  { f: "Harsh", l: "Vardhan", g: "male", s: ["Go", "Kubernetes", "gRPC", "Prometheus"], a: "Backend platform engineer scaling Kubernetes clusters across clouds." },
  { f: "Anurag", l: "Shukla", g: "male", s: ["Next.js", "Supabase", "TypeScript", "Tailwind"], a: "Indie builder launching developer tools and micro-SaaS utilities." },
  { f: "Ritika", l: "Saxena", g: "female", s: ["Python", "FastAPI", "PyTorch", "Docker"], a: "Machine learning engineer building production inference APIs." },
  { f: "Naveen", l: "Kumar", g: "male", s: ["Flutter", "Dart", "Firebase", "State Management"], a: "Mobile app developer building offline-first apps for Bharat users." },
  { f: "Monika", l: "Chauhan", g: "female", s: ["React", "Redux", "TypeScript", "Jest"], a: "Frontend lead obsessed with component modularity and zero tech debt." },
  { f: "Rajat", l: "Sharma", g: "male", s: ["Java", "Spring Boot", "Kafka", "AWS"], a: "Enterprise backend developer engineering low-latency messaging backbones." },
  { f: "Sakshi", l: "Tiwari", g: "female", s: ["Design Systems", "Figma", "Product Strategy"], a: "Product designer crafting seamless onboarding and activation flows." },
  { f: "Vikrant", l: "Gupta", g: "male", s: ["Rust", "Tokio", "WebSockets", "C++"], a: "Systems programmer writing high-throughput financial market gateways." },
  { f: "Ankita", l: "Roy", g: "female", s: ["PostgreSQL", "Database Optimization", "Redis"], a: "Database engineer tuning complex relational schemas for scale." },
  { f: "Mayank", l: "Agarwal", g: "male", s: ["Solidity", "EVM", "Ethereum", "Hardhat"], a: "Web3 developer writing gas-optimized smart contracts and DeFi protocols." },
  { f: "Pooja", l: "Vaidya", g: "female", s: ["Next.js", "React", "GraphQL", "Tailwind"], a: "Frontend developer building blazing-fast headless commerce experiences." },
  { f: "Rohit", l: "Verma", g: "male", s: ["Cybersecurity", "Penetration Testing", "Linux"], a: "Ethical hacker and security researcher discovering zero-days." },
  { f: "Isha", l: "Pandey", g: "female", s: ["Content Strategy", "Developer Advocacy", "Docs"], a: "DevRel specialist connecting technical communities with cloud tools." },
  { f: "Deepak", l: "Joshi", g: "male", s: ["Python", "Django", "PostgreSQL", "Celery"], a: "Full-stack engineer building automated reporting and workflow tools." },
  { f: "Neha", l: "Kapoor", g: "female", s: ["PyTorch", "NLP", "HuggingFace", "Python"], a: "Data scientist developing sentiment analysis and summarization pipelines." },
  { f: "Vivek", l: "Malik", g: "male", s: ["Node.js", "Express", "MongoDB", "Socket.io"], a: "Real-time backend developer passionate about distributed chat architectures." },
  { f: "Sanya", l: "Mirza", g: "female", s: ["React Native", "iOS", "Android", "TypeScript"], a: "Mobile developer creating high-performance consumer applications." },
  { f: "Tarun", l: "Bansal", g: "male", s: ["Terraform", "AWS", "Docker", "CI/CD"], a: "Cloud engineer automating multi-tenant infrastructure deployments." },
  { f: "Komal", l: "Purohit", g: "female", s: ["A11y", "HTML5", "CSS3", "JavaScript"], a: "Frontend accessibility advocate ensuring web access for everyone." },
  { f: "Siddhesh", l: "Patil", g: "male", s: ["C++", "OpenGL", "Algorithms", "Graphics"], a: "Graphics programmer building real-time rendering engines." },
  { f: "Swati", l: "Deshpande", g: "female", s: ["Technical Writing", "API Specs", "Git"], a: "Technical communicator bridging developers and product stakeholders." },
  { f: "Ashwin", l: "Raman", g: "male", s: ["Go", "Distributed Systems", "Consensus", "gRPC"], a: "Distributed systems engineer working on consensus and replication." },
  { f: "Bhavika", l: "Patel", g: "female", s: ["Vue.js", "Nuxt.js", "Tailwind CSS", "Pinia"], a: "Frontend developer passionate about Vue ecosystem and lightweight UIs." },
  { f: "Gautam", l: "Kashyap", g: "male", s: ["Python", "Spark", "Airflow", "Data Lakes"], a: "Big data engineer building petabyte-scale analytics pipelines." },
  { f: "Meenal", l: "Kulkarni", g: "female", s: ["Product Management", "Scrum", "Analytics"], a: "Product owner shipping high-impact B2B SaaS features." },
  { f: "Prateek", l: "Chawla", g: "male", s: ["React", "Node.js", "GraphQL", "MongoDB"], a: "MERN stack engineer building collaborative workspace tools." },
  { f: "Jyoti", l: "Yadav", g: "female", s: ["Automated QA", "Playwright", "Jest", "CI"], a: "Test architect building continuous testing harnesses for microservices." },
  { f: "Hemant", l: "Soni", g: "male", s: ["Flutter", "Firebase", "Dart", "Clean Architecture"], a: "Mobile engineer building e-commerce and delivery tracking apps." },
  { f: "Rashmi", l: "Nambiar", g: "female", s: ["Computer Vision", "PyTorch", "Python"], a: "AI researcher focusing on medical imaging and cancer detection models." },
  { f: "Kartik", l: "Bhat", g: "male", s: ["Node.js", "TypeScript", "Redis", "Microservices"], a: "Backend developer architecting event-driven microservices." },
  { f: "Tanvi", l: "Mahajan", g: "female", s: ["Figma", "Interaction Design", "User Research"], a: "UX researcher unearthing customer friction points and prototyping fixes." },
  { f: "Yash", l: "Singhal", g: "male", s: ["Next.js", "React", "Server Actions", "Vite"], a: "Frontend speed demon obsessed with 100/100 Lighthouse scores." },
  { f: "Aishwarya", l: "Nath", g: "female", s: ["Python", "LangChain", "Vector DBs", "OpenAI"], a: "Generative AI engineer building conversational copilots for enterprise." },
  { f: "Nitin", l: "Gadkari", g: "male", s: ["System Design", "Cloud Architecture", "Leadership"], a: "Infrastructure builder scaling high-capacity networks and reliability." },
  { f: "Shilpa", l: "Shetty", g: "female", s: ["Wellness Tech", "Product Strategy", "Consumer"], a: "Building mindful digital apps for fitness and health routines." },
  { f: "Umesh", l: "Yadav", g: "male", s: ["High Speed Streaming", "WebSockets", "Go"], a: "Streaming media engineer building ultra low-latency video distribution." },
  { f: "Geeta", l: "Phogat", g: "female", s: ["Discipline", "Engineering Management", "Agile"], a: "Engineering leader instilling relentless discipline and high code quality." },
  { f: "Brijesh", l: "Tripathi", g: "male", s: ["Rust", "WASM", "Systems", "Compilers"], a: "WebAssembly researcher bringing desktop software runtimes to the browser." },
  { f: "Preeti", l: "Nair", g: "female", s: ["Cloud Architecture", "AWS", "Security", "IAM"], a: "Solutions architect crafting resilient multi-account AWS topologies." },
  { f: "Manav", l: "Chopra", g: "male", s: ["Next.js", "Prisma", "PostgreSQL", "Tailwind"], a: "Full stack builder turning startup MVPs into scalable web apps." },
  { f: "Kiran", l: "Bedi", g: "female", s: ["Governance", "Security Auditing", "Compliance"], a: "Security auditor establishing robust data protection and governance." },
  { f: "Sanjay", l: "Dutt", g: "male", s: ["Resilience", "Disaster Recovery", "Cloud Ops"], a: "Site reliability engineer specializing in chaos engineering and failover." },
  { f: "Lata", l: "Mangeshkar", g: "female", s: ["Audio Engineering", "DSP", "Music Tech"], a: "Digital signal processing engineer building high-fidelity audio codecs." },
  { f: "Farhan", l: "Akhtar", g: "male", s: ["Creative Direction", "UI/UX", "Brand Design"], a: "Multidisciplinary designer and storyteller building emotional web apps." },
  { f: "Zoya", l: "Akhtar", g: "female", s: ["User Research", "Narrative Design", "Product"], a: "Narrative designer creating immersive user journeys and brand voice." },
  { f: "Shahrukh", l: "Khan", g: "male", s: ["Product Evangelism", "Public Speaking", "Strategy"], a: "Chief Evangelist connecting global audiences with breakthrough technology." },
  { f: "Juhi", l: "Chawla", g: "female", s: ["Sustainable Tech", "Clean Energy", "IoT"], a: "IoT engineer building energy monitoring sensors and green tech solutions." },
  { f: "Ranveer", l: "Singh", g: "male", s: ["High Energy Shipping", "Frontend", "Animation"], a: "Hyper-energetic developer crafting jaw-dropping motion design and animations." },
  { f: "Deepika", l: "Padukone", g: "female", s: ["Mental Health Tech", "Design", "Consumer"], a: "Product strategist building supportive communities and mental health tools." },
  { f: "Hrithik", l: "Roshan", g: "male", s: ["Computer Graphics", "Motion Capture", "VFX"], a: "Computer graphics specialist pushing the frontiers of visual realism." },
  { f: "Katrina", l: "Kaif", g: "female", s: ["Beauty Tech", "D2C Architecture", "E-Commerce"], a: "E-commerce architect building high-conversion retail checkouts." },
  { f: "Ranbir", l: "Kapoor", g: "male", s: ["Mobile Architecture", "Swift", "Kotlin"], a: "Mobile lead building next-generation consumer apps with native precision." },
  { f: "Alia", l: "Bhatt", g: "female", s: ["Brand Growth", "Eco Tech", "Product Design"], a: "Sustainable fashion and tech entrepreneur scaling eco-conscious consumer apps." },
];

const portraitUrls = {
  male: [
    "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&crop=faces&w=800&q=80",
    "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&crop=faces&w=800&q=80",
    "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&crop=faces&w=800&q=80",
    "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&crop=faces&w=800&q=80",
    "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&crop=faces&w=800&q=80",
    "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&crop=faces&w=800&q=80",
    "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&crop=faces&w=800&q=80",
    "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&crop=faces&w=800&q=80",
    "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&crop=faces&w=800&q=80",
  ],
  female: [
    "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&crop=faces&w=800&q=80",
    "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&crop=faces&w=800&q=80",
    "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&crop=faces&w=800&q=80",
    "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&crop=faces&w=800&q=80",
    "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&crop=faces&w=800&q=80",
  ],
};

// Build the extended list
additionalIndianNames.forEach((person, idx) => {
  const images = portraitUrls[person.g];
  const selectedImage = images[idx % images.length];
  const emailName = person.f.toLowerCase();
  mockUsers.push({
    firstName: person.f,
    lastName: person.l,
    email: `${emailName}${idx + 1}@gmail.com`,
    plainPassword: `${emailName}@123`,
    age: 23 + (idx % 18),
    gender: person.g,
    about: person.a,
    lookingFor: "Technical Co-founders & Collaborators",
    skills: person.s,
    profilePictureUrl: selectedImage,
    membershipType: idx % 3 === 0 ? "pro" : "basic",
  });
});

async function seedDatabase() {
  try {
    console.log(`Connecting to MongoDB... Total users to seed: ${mockUsers.length}`);
    await ConnectDB();
    console.log("Connected successfully!");

    console.log("Clearing existing users, connection requests, and chats...");
    await User.deleteMany({});
    await ConnectionRequest.deleteMany({});
    await Chat.deleteMany({});
    console.log("Collections cleared successfully!");

    console.log("Hashing passwords and seeding user profiles...");
    const usersToInsert = await Promise.all(
      mockUsers.map(async (u) => {
        const passwordHash = await bcrypt.hash(u.plainPassword, 10);
        return {
          firstName: u.firstName,
          lastName: u.lastName,
          email: u.email.toLowerCase().trim(),
          password: passwordHash,
          age: u.age,
          gender: u.gender,
          about: u.about,
          lookingFor: u.lookingFor,
          skills: u.skills,
          profilePictureUrl: u.profilePictureUrl,
          membershipType: u.membershipType || "basic",
        };
      })
    );

    const insertedUsers = await User.insertMany(usersToInsert);
    console.log(`Successfully seeded ${insertedUsers.length} users into Orbit database!`);

    // Create mutual accepted connections for dev@gmail.com so test chat & connections work out-of-the-box
    const devUser = insertedUsers.find((u) => u.email === "dev@gmail.com");
    if (devUser) {
      const connectionsToSeed = [
        "elon@gmail.com",
        "sarah@gmail.com",
        "kunal@gmail.com",
        "priya@gmail.com",
        "deepinder@gmail.com",
        "grace@gmail.com",
        "linus@gmail.com",
        "guillermo@gmail.com",
        "radhika@gmail.com",
        "ananya@gmail.com",
      ];

      const connectionDocs = [];
      for (const email of connectionsToSeed) {
        const target = insertedUsers.find((u) => u.email === email);
        if (target) {
          connectionDocs.push({
            fromUserId: target._id,
            toUserId: devUser._id,
            status: "accepted",
          });
        }
      }

      // Add a couple pending requests for Requests screen
      const pendingUsers = ["sam@gmail.com", "jensen@gmail.com", "nikhil@gmail.com"];
      for (const email of pendingUsers) {
        const target = insertedUsers.find((u) => u.email === email);
        if (target) {
          connectionDocs.push({
            fromUserId: target._id,
            toUserId: devUser._id,
            status: "interested",
          });
        }
      }

      await ConnectionRequest.insertMany(connectionDocs);
      console.log(`Successfully seeded ${connectionDocs.length} initial connection requests for dev@gmail.com!`);
    }

    console.log("\n--- Top Demo Accounts ---");
    mockUsers.slice(0, 20).forEach((u) => {
      console.log(`Email: ${u.email.padEnd(25)} Password: ${u.plainPassword}`);
    });
    console.log("-------------------------\n");
  } catch (error) {
    console.error("Error seeding database:", error);
  } finally {
    await mongoose.disconnect();
    console.log("Disconnected from MongoDB.");
    process.exit(0);
  }
}

seedDatabase();
